### ISSUE TITLE
Minor issue: LICENSE

### ISSUE THREAD

**Issue by rrrlw** [nhejazi/medoutcon#32]
The MIT license is appropriate. However, you need a copy of the plaintext license (https://opensource.org/licenses/MIT) in the repository per JOSS guidelines.

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3979).

**Comment by rrrlw** [comment]
I now see the MIT license in the README - moving it to the LICENSE file or a new LICENSE.md file should be sufficient.

**Comment by nhejazi** [comment]
Thanks for pointing this out, I'd neglected to include a `LICENSE.md` file but agree that it's a good practice. This has been addressed in b990c07 of #34.
