### ISSUE TITLE
Optional issue: examples

### ISSUE THREAD

**Issue by rrrlw** [nhejazi/medoutcon#33]
A comprehensive example is provided in the README. However, users of the R package would also benefit from quick access to examples in the documentation itself (i.e. using the `@example` or `@examples` Roxygen tag so that it can be accessed with `?<function name>`).

If adding an example within the documentation is too complex, you can simply close this issue.

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3979).

**Comment by nhejazi** [comment]
Thanks for pointing this out. As someone who does access examples through the R documentation, I agree that it would be very useful to have these for the exported functions (of which there are only 3, `medoutcon`, `est_tml`, and `est_onestep`). I'll add these later today and update once that has been completed.

**Comment by nhejazi** [comment]
In 0980f97 of #34, I removed the exporting of the internal estimation functions `est_tml()` and `est_onestep()`, and I added an example based on the `README` to the eponymous function `medoutcon()`.
